name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'docker.compose.yml'
      - '.github/workflows/**'
      - '.github/scripts/**'
      - '!**.md'
      - '!**/.gitignore'

jobs:
  call-deploy:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: frontend
      context: ./frontend
      image_name: ${{ github.repository }}-frontend
    secrets: inherit
