name: Deploy Monorepo

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker.compose.yml'
      - '.github/workflows/**'
      - '.github/scripts/**'
      - '!**.md'
      - '!**/.gitignore'

jobs:
  quality:
    name: Lint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma client
        run: pnpm -r postinstall
      - name: Quality Check
        run: |
          pnpm --filter @bnr-portal/frontend lint
          pnpm --filter @bnr-portal/frontend typecheck
          pnpm --filter @bnr-portal/backend lint
          pnpm --filter @bnr-portal/backend typecheck

  detect-changes:
    needs: quality
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'docker.compose.yml'
              - '.github/**'
            frontend:
              - 'frontend/**'
              - 'docker.compose.yml'
              - '.github/**'

  deploy-backend:
    needs: [quality, detect-changes]
    if: needs.detect-changes.outputs.backend == 'true'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: backend
      context: ./backend
      image_name: ${{ github.repository }}-backend
      project_name: ${{ github.event.repository.name }}
    secrets: inherit

  deploy-frontend:
    needs: [quality, detect-changes]
    # Run if frontend changed
    if: needs.detect-changes.outputs.frontend == 'true'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      service_name: frontend
      context: ./frontend
      image_name: ${{ github.repository }}-frontend
      project_name: ${{ github.event.repository.name }}
    secrets: inherit
