name: Reusable SSH Deploy

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      project_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate .env file
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}
          TARGET_ENV: production
          APP_NAME: ${{ inputs.project_name }}
        run: |
          chmod +x .github/scripts/generate-env.sh
          ./.github/scripts/generate-env.sh
          chmod 644 .env.production

      - name: Copy deploy script to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: ".github/scripts/deploy.sh,docker.compose.yml,.env.production"
          target: "/opt/deploy/${{ inputs.project_name }}"
          strip_components: 0

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /opt/deploy/${{ inputs.project_name }}
            chmod +x .github/scripts/deploy.sh
            ./.github/scripts/deploy.sh ${{ inputs.service_name }} ${{ github.sha }} ${{ github.event.repository.name }}
